export async function GET() {
  const metadata = {
    file: {
      name: "train_delays_2024.csv",
      size_bytes: 54525952,
      row_count: 248310,
      column_count: 12,
    },
    columns: [
      {
        name: "train_id",
        dtype: "string",
        null_count: 0,
        unique_count: 5420,
        top_values: ["IC-1801", "SPR-3042", "IC-0024", "THA-0901", "INT-0312"],
      },
      {
        name: "departure_time",
        dtype: "datetime",
        null_count: 87,
        unique_count: 86_400,
        min: "2024-01-01T04:00:00",
        max: "2024-12-31T23:59:00",
      },
      {
        name: "arrival_time",
        dtype: "datetime",
        null_count: 124,
        unique_count: 86_400,
        min: "2024-01-01T04:12:00",
        max: "2025-01-01T00:42:00",
      },
      {
        name: "delay_minutes",
        dtype: "numeric",
        null_count: 3_412,
        unique_count: 94,
        min: -5,
        max: 187,
        mean: 4.3,
        std: 11.8,
        median: 1,
      },
      {
        name: "station_from",
        dtype: "string",
        null_count: 0,
        unique_count: 402,
        top_values: ["Amsterdam Centraal", "Utrecht Centraal", "Rotterdam Centraal"],
      },
      {
        name: "station_to",
        dtype: "string",
        null_count: 0,
        unique_count: 402,
        top_values: ["Den Haag Centraal", "Eindhoven", "Schiphol Airport"],
      },
      {
        name: "platform",
        dtype: "string",
        null_count: 1_204,
        unique_count: 26,
        top_values: ["1", "2", "3", "4a", "4b"],
      },
      {
        name: "train_type",
        dtype: "categorical",
        null_count: 0,
        unique_count: 6,
        top_values: ["Intercity", "Sprinter", "Intercity Direct", "Thalys", "NS International", "Eurostar"],
      },
      {
        name: "cancelled",
        dtype: "boolean",
        null_count: 0,
        unique_count: 2,
        top_values: ["false", "true"],
      },
      {
        name: "passenger_count",
        dtype: "numeric",
        null_count: 12_480,
        unique_count: 845,
        min: 0,
        max: 1_024,
        mean: 287.4,
        std: 198.2,
        median: 263,
      },
      {
        name: "operator",
        dtype: "categorical",
        null_count: 0,
        unique_count: 4,
        top_values: ["NS", "Arriva", "Connexxion", "Keolis"],
      },
      {
        name: "route_distance_km",
        dtype: "numeric",
        null_count: 320,
        unique_count: 188,
        min: 2.1,
        max: 312.4,
        mean: 78.3,
        std: 61.7,
        median: 62.5,
      },
    ],
  };

  return Response.json(metadata);
}
